calimero-is-near/VM

src/lib/data/near.js
webpack.config.js

Fixed typos causing build errors + added path for dotenv config as ".env" is not used

fix: webpack build error

---

Dockerfile

Replace near-discovery with calimero-portal

feat(bos-gateway): replace near-discovery with calimero-portal

---

infra/k8s/environments/gcp/production/internal/kustomization.yaml
infra/k8s/environments/gcp/production/portal/kustomization.yaml
infra/k8s/environments/gcp/staging/kustomization.yaml

Update values for stage and prod. 
Linked staging to new chain with working wallet.

feat(bos-gateway): update kustomization env variables

---

infra/k8s/environments/gcp/production/internal/kustomization.yaml
infra/k8s/environments/gcp/production/kustomization.yaml

this image points to correct bos encryption url

infra: patch docker image on internal production gw

---

src/index.js
src/lib/components/Widget.js
src/lib/components/globalState.js
src/lib/vm/vm.js

Integration of `GlobalStateContext` to manage global state within the application using the contextAPI.
* Created a new `GlobalStateContext` to enable centralized state management.
* export of `GlobalStateContext` to allow Gateway inject the GlobalState into the root widget.
* Introduced the use of `GlobalStateContext` to access and manage global state within widgets.
* Extended VM to support the `GlobalStateProvider` and the new `useGlobalState` method.
**Creating the context within a widget**:
```jsx
const ThemeNameDisplay = () => {
const [theme] = useGlobalState("theme");
return <div>Current theme is: {theme}</div>;
};
const LigthThemeButton = () => {
const [_, setTheme] = useGlobalState("theme");
return <button onClick={() => setTheme("light")}>Set Light Theme</button>;
};
const …
```

feat: initial version of globalState hook

---

Dockerfile.buildtime-config

Fix issue with build caused by missing file from portal

fix: missing file from portal during build

---

src/lib/vm/vm.js

Reverts calimero-is-near/VM#122

fix: Revert Reverts calimero-is-near/VM#122

---

package.json

Upgrade VM to include next version of chat list 0.0.0-alpha.2

feat(VM): update chat list dependencies

---

src/lib/components/md-editor.css

Connected to [this](https://github.com/calimero-is-near/PortalApps/pull/241) PR

feat: update markdown inputfield padding

---

package.json
src/lib/vm/vm.js
yarn.lock

expose library function to create a message renderer compatible with CubMessage and the virtualized list.

feat: expose  message renderer

---

src/lib/vm/vm.js

Exposing message tag from virtualized-chat lib thats used for threads header

feat: expose message tag

---

src/lib/components/MarkdownEditor.js

Connected with this [PR](https://github.com/calimero-is-near/PortalApps/pull/343) 
Fixes # [AM-2003](https://calimero.atlassian.net/browse/AM-2003)

fix: remove clear message on enter

---

package.json
yarn.lock

Updated chatlib to newest version

fix: bump chatlib v35

---

src/lib/vm/vm.js

feat(bos-gateway): exposing inner get

---

package.json
yarn.lock

fix: bump chatlib v41

---

infra/k8s/environments/gcp/production/kustomization.yaml

Reverts calimero-is-near/VM#207

Revert "chore(bos-gateway-public-production): automated version bump"

---

package.json
yarn.lock

fix: bump chatlib v45

---

src/lib/components/MarkdownEditor.js

Code cleanup as it is no longer used. Apps [PR](https://github.com/calimero-is-near/PortalApps/pull/435)
Fixes # [DEV-159](https://calimero.atlassian.net/browse/DEV-159)

fix: emojis new line code cleanup

---

infra/k8s/environments/gcp/production/kustomization.yaml

Reverts calimero-is-near/VM#250

Revert "chore(bos-gateway-internal-production): manual version bump"

---

package.json

Tested with npm run webpack -- --env mode=production and compiled successfuly

fix(bos-gateway): add stream-browsify to deps
